package use_case.quiz.generate;

import io.github.cdimascio.dotenv.Dotenv;
import org.apache.http.HttpEntity;
import org.apache.http.HttpHeaders;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;
import org.json.JSONArray;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.InputStreamReader;

/**
 * The Chatbot class interacts with the OpenAI GPT model to generate responses based on user input.
 * This class is executed in the GenerateQuizInteractor.
 */
public class GPT implements TextGeneratorEndpoints{
    /** The Dotenv instance for loading environment variables. */
    static Dotenv dotenv = Dotenv.load();

    /** The OpenAI API key. */
    private static final String OPENAI_API_KEY = dotenv.get("OPENAI_API_KEY");

    /** The OpenAI GPT endpoint for chat completions. */
    private static final String OPENAI_ENDPOINT = "https://api.openai.com/v1/chat/completions";

    /**
     * The main method to demonstrate the Chatbot functionality.
     *
     * @param args Command-line arguments (not used).
     */
    public static void main(String[] args) {
        try {
            GPT gpt = new GPT();
            String userInput = gpt.getUserInput();
            String response = gpt.getChatGPTResponse(userInput);

            System.out.println("ChatGPT: " + response);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Default constructor for the Chatbot class.
     */
    public GPT(){
    }

    /**
     * Reads user input from the console.
     *
     * @return User input as a String.
     * @throws Exception If an error occurs while reading input.
     */
    @Override
    public String getUserInput() throws Exception {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        System.out.print("You: ");
        return reader.readLine();
    }

    /**
     * Obtains a response from the OpenAI GPT model based on the provided user input.
     *
     * @param userInput The user input for generating a response.
     * @return The response generated by the GPT model.
     * @throws Exception If an error occurs during the interaction with the GPT model.
     */
    @Override
    public String getChatGPTResponse(String userInput) throws Exception {
        String apiKey = OPENAI_API_KEY;
        String model = "gpt-4-1106-preview";
        String prompt = "[{\"role\": \"user\", \"content\": \"" + userInput + "\"}]";
        int maxTokens = 3000;

        String requestBody = "{\"model\": \"" + model + "\", \"messages\": " + prompt + ", \"max_tokens\": " + maxTokens + "}";

        HttpClient httpClient = HttpClients.createDefault();
        HttpPost httpPost = new HttpPost(OPENAI_ENDPOINT);

        httpPost.setHeader(HttpHeaders.AUTHORIZATION, "Bearer " + apiKey);
        httpPost.setHeader(HttpHeaders.CONTENT_TYPE, "application/json");

        httpPost.setEntity(new StringEntity(requestBody));

        HttpResponse httpResponse = httpClient.execute(httpPost);
        HttpEntity responseEntity = httpResponse.getEntity();

        if (responseEntity != null) {

            String response = EntityUtils.toString(responseEntity);
            String apiResponse = response;
            JSONObject jsonResponse = new JSONObject(apiResponse);
            EntityUtils.consume(responseEntity);
            JSONArray choices = jsonResponse.getJSONArray("choices");
            JSONObject firstChoice = choices.getJSONObject(0);
            JSONObject message = firstChoice.getJSONObject("message");
            String content = message.getString("content");
            return content;
        } else {
            throw new IllegalStateException("Empty response entity");
        }
    }
}